[workspace]
resolver = "3"
members = ["crates/*", "lazycard"]
default-members = ["lazycard"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
# todo: add msrs and other fields

[workspace.dependencies]
ahash = {
  version = "0.8",
  default-features = false,
  features = ["runtime-rng", "std"]
}
base64 = {
  version = "0.22",
  default-features = false,
  features = ["alloc", "std"]
}
clap = {
  version = "4.6",
  default-features = false,
  features = ["color", "derive", "error-context", "help", "std", "usage"]
}
clap-cargo = { version = "0.18", default-features = false }
constcat = { version = "0.6", default-features = false }
database = { path = "crates/database", default-features = false }
directories = { version = "6.0", default-features = false }
edit = { version = "0.1", default-features = false, features = ["better-path"] }
fsrs = { version = "6.6", default-features = false }
image = {
  version = "0.25",
  default-features = false,
  features = [
    "gif",
    "jpeg",
    "png",
    "rayon",
    "webp",
  ]
}
itoa = { version = "1.0", default-features = false }
nucleo-matcher = {
  version = "0.3",
  default-features = false,
  features = [
    "unicode-casefold",
    "unicode-normalization",
    "unicode-segmentation"
  ]
}
ratatui = {
  version = "0.30",
  default-features = false,
  features = ["crossterm", "serde"]
}
ron = { version = "0.12", default-features = false, features = ["std"] }
rusqlite = {
  version = "0.40",
  default-features = false,
  features = ["bundled", "cache"]
}
seahash = { version = "4.1", default-features = false }
serde = {
  version = "1.0",
  default-features = false,
  features = ["derive", "std"]
}
syntect = {
  version = "5.3",
  default-features = false,
  features = ["default-syntaxes", "default-themes", "parsing", "regex-onig"]
}
terminal-colorsaurus = { version = "1.0", default-features = false }
textwrap = {
  version = "0.16",
  default-features = false,
  features = ["smawk", "unicode-linebreak", "unicode-width"]
}
toml = {
  version = "1.1",
  default-features = false,
  features = ["display", "parse", "serde", "std"]
}
unicode-segmentation = { version = "1.13", default-features = false }
unicode-width = { version = "0.2", default-features = false }
utils = { path = "crates/utils", default-features = false }
widgets = { path = "crates/widgets", default-features = false }
zlib-rs = {
  version = "0.6",
  default-features = false,
  features = ["c-allocator", "std"]
}

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1
