[package]
name = "lazycard"
version = "0.1.0"
edition = "2021"
# todo: add msrs and other fields

[dependencies]
arboard = { version = "3.6", default-features = false }
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
edit = "0.1"
fastrand = "2.3"
fsrs = "5.1"
nucleo-matcher = "0.3"
ratatui = { version = "0.29", features = ["unstable-widget-ref"] }
ron = "0.10"
serde = { version = "1.0", features = ["derive"] }
syntect = "5.2"
terminal-colorsaurus = "1.0"
unicode-segmentation = "1.12"
unicode-width = "0.2"
