[package]
name = "widgets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ahash = { workspace = true }
base64 = { workspace = true }
image = { workspace = true }
itoa = { workspace = true }
ratatui = { workspace = true }
seahash = { workspace = true }
syntect = { workspace = true }
textwrap = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
utils = { workspace = true }
zlib-rs = { workspace = true }
