[package]
name = "widgets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arboard = { workspace = true }
itoa = { workspace = true }
ratatui = { workspace = true }
seahash = { workspace = true }
syntect = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
